[package]
name = "delete_user"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lambda_http = "0.4.1"
lambda_runtime = "0.4.1"
serde = "1.0.134"
serde_json = "1.0.75"
tokio = "1.15.0"
